version: '3'
services:
  web:
    container_name: 'accman-web-app'
    image: 'accman-web'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:80'
    depends_on:
      - 'postgres'
    networks:
      - accman-network  

  postgres:
    ports:
      - '5432:5432'
    container_name: accman-postgresql
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - 'accman-postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:latest'
    networks:
      - accman-network

volumes:
  accman-postgresql-volume:

networks:
  accman-network:
    driver: bridge
