version: "3"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=appuser
      - POSTGRES_DB=ReturnOrderManagementDb
    ports:
      - "5432:5432"
  api:
    container_name: api
    platform: linux/x86_64
    image: superacr2.azurecr.io/api
    restart: always
    build:
      context: .

    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # web:
  #   container_name: web
  #   restart: unless-stopped
  #   build:
  #    context: client
  #   ports:
  #     - '4200:80'
  #   depends_on:
  #     - api

