version: "3.8"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=appuser
      - POSTGRES_DB=ReturnOrderManagementDb
    ports:
      - "5439:5432"
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .

    ports:
      - 6578:8800
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
      - ASPNETCORE_URLS=http://+:8800
    depends_on:
      - database
  # web:
  #   container_name: web
  #   restart: unless-stopped
  #   build:
  #    context: client
  #   ports:
  #     - '4200:80'
  #   depends_on:
  #     - api

