apiVersion: apps/v1
kind: Deployment
metadata:
  name: seshademo
  labels:
    app: seshademo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seshademo
  template:
    metadata:
      labels:
        app: seshademo
    spec:
      containers:
      - name: seshademo
        image: seshademo.azurecr.io/seshademo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: seshademo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: seshademo